services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventos-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6100:1433" # host:contenedor — cambiado porque 1433 ya estaba ocupado en tu PC.
                   
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$DB_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventos-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:6000

      ConnectionStrings__DefaultConnection: "Server=db;Database=EventosDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;"
      Jwt__Key: ${JWT_KEY}
    ports:
      - "6101:6000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventos-frontend
    depends_on:
      - backend
    ports:

      - "6767:80"

volumes:
  mssql_data: